@startuml

class FeatureCloud {
  computeSufraceNormals()
  ExtractKeypoints()
  computeDescriptors()
}

class FeatureMatching {
  initialAlignment()
  divideFullModelIntoBlocks()
  findBestAlignment()
}

class ICP {
  Align()
}

class MapsIntegrator {
  Merge()
  EstimateTransformation()
  DumpConfigAndResultsToFile()
  GetConfigurationFromRosParams()
}

class 3DMapsVisualizer {
	Visualize()
	VisualizeICP()
	VisualizeFeatureMatching()
	VisualizeFeatureMatchingWithDividedModel()
	VisualizeClouds()
}

' Connections
FeatureMatching o-- FeatureCloud

MapsIntegrator o-- GlobalAlignment
GlobalAlignment <|-- FeatureMatching

MapsIntegrator o-- LocalAlignment
LocalAlignment <|-- ICP
LocalAlignment <|-- OICP

MapsIntegrator o-- 3DMapsVisualizer

MapsServer -.> MapsIntegrator
MapsServer *-- Graph
MapsServer o-- Map

Map o-- Octomap
Map o-- PointCloud

@enduml