@startuml

class FeatureCloud {
  computeSufraceNormals()
  ExtractKeypoints()
  computeDescriptors()
}

class FeatureMatching {
  initialAlignment()
  divideFullModelIntoBlocks()
  findBestAlignment()
}

class ICP {
  Align()
}

class NDT {
  Align()
}

class AlignmentMethod {
  Align()
}

class GlobalAlignment {
  Align()
}

class LocalAlignment {
  Align()
}

class TransformationEstimator {
  EstimateTransformation()
}

class MapsIntegrator {
  Merge()
  EstimateTransformation()
  DumpConfigAndResultsToFile()
  GetConfigurationFromRosParams()
}

class 3DMapsVisualizer {
	Visualize()
	' VisualizeICP()
	' VisualizeFeatureMatching()
	' VisualizeFeatureMatchingWithDividedModel()
	' VisualizeClouds()
}

' Connections

MapServerNode o-- MapServer

MapServer -.> MapsIntegrator
MapServer *-- Graph

Graph o-- Pose
Graph o-- Map

MapsIntegrator -- TransformationEstimator
MapsIntegrator o-- 3DMapsVisualizer

TransformationEstimator o-- GlobalAlignment
TransformationEstimator o-- LocalAlignment

AlignmentMethod <|-- GlobalAlignment
AlignmentMethod <|-- LocalAlignment

LocalAlignment <|-- ICP

GlobalAlignment <|-- FeatureMatching
GlobalAlignment <|-- NDT

FeatureMatching o-- FeatureCloud
FeatureCloud -- PointCloud



Map o-- Octomap
Map o-- PointCloud

@enduml