@startuml

class FeatureCloud {
  ExtractKeypoints()
  ComputeDescriptors()
}

class FeatureMatching {
  Align()
  DivideFullModelIntoBlocks()
  FindBestAlignment()
}

class ICP {
  Align()
}

class NDT {
  Align()
}

class AlignmentMethod {
  Align()
}

class GlobalAlignment {
  Align()
}

class LocalAlignment {
  Align()
}

class TransformationEstimator {
  EstimateTransformation()
}

class MapsIntegrator {
  Merge()
  EstimateTransformation()
}

class 3DMapsVisualizer {
	Visualize()
}

' Connections

MapServerNode *-- MapServer

MapServer -.> MapsIntegrator
MapServer *-- Graph

Graph o-- Pose
Graph o-- Map

MapsIntegrator --> TransformationEstimator
MapsIntegrator o-- 3DMapsVisualizer

TransformationEstimator --> GlobalAlignment
TransformationEstimator --> LocalAlignment

AlignmentMethod <|-- GlobalAlignment
AlignmentMethod <|-- LocalAlignment

LocalAlignment <|-- ICP

GlobalAlignment <|-- FeatureMatching
GlobalAlignment <|-- NDT

FeatureMatching --> FeatureCloud
FeatureCloud o-- PointCloud

Map o-- Octomap
Map o-- PointCloud

@enduml